import { dark } from "@clerk/themes";

export const skyluxeClerkAppearance = {
  baseTheme: dark,
  variables: {
    colorBackground: "#09090b",
    colorInputBackground: "#121215",
    colorInputText: "#ffffff",
    colorText: "#ffffff",
    colorTextSecondary: "#a1a1aa",
    colorPrimary: "#D4AF37",
    colorTextOnPrimaryBackground: "#050505",
    colorDanger: "#f87171",
    colorSuccess: "#34d399",
    borderRadius: "0.875rem",
    fontFamily: '"Satoshi", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  elements: {
    card: "!bg-[#09090b]/95 !backdrop-blur-2xl !border !border-[#D4AF37]/25 !shadow-[0_0_50px_rgba(0,0,0,0.9),0_0_30px_rgba(212,175,55,0.08)] rounded-3xl p-8 max-w-[460px] w-full transition-all duration-300",
    rootBox: "w-full flex justify-center",
    headerTitle: "!text-white font-serif !text-2xl lg:!text-3xl font-bold tracking-tight !mb-1.5",
    headerSubtitle: "!text-zinc-400 text-xs font-light tracking-wide",
    socialButtonsBlockButton: "!bg-[#141417] !border !border-white/10 hover:!border-[#D4AF37]/60 hover:!bg-[#1c1c22] !text-white rounded-xl transition-all duration-300 py-3.5 shadow-sm group",
    socialButtonsBlockButtonText: "!text-zinc-200 text-sm font-medium tracking-wide group-hover:!text-white",
    socialButtonsProviderIcon: "!w-4 !h-4 transition-transform group-hover:scale-110",
    dividerLine: "!bg-gradient-to-r !from-transparent !via-zinc-700 !to-transparent",
    dividerText: "!text-zinc-500 text-[10px] uppercase tracking-[0.2em] font-mono",
    formFieldLabel: "!text-zinc-300 text-xs font-mono uppercase tracking-wider mb-2",
    formFieldInput: "!bg-[#121215] !border !border-white/10 !text-white rounded-xl focus:!border-[#D4AF37] focus:!ring-2 focus:!ring-[#D4AF37]/30 transition-all text-sm py-3.5 px-4 placeholder:!text-zinc-600 shadow-inner",
    formButtonPrimary: "!bg-gradient-to-r !from-[#D4AF37] !via-[#E5C358] !to-[#F3E5AB] !text-black font-bold text-sm tracking-wider uppercase rounded-xl py-3.5 !shadow-[0_0_30px_rgba(212,175,55,0.35)] hover:!shadow-[0_0_45px_rgba(212,175,55,0.6)] hover:-translate-y-0.5 active:translate-y-0 transition-all duration-300 !border-0 cursor-pointer",
    footerActionLink: "!text-[#D4AF37] hover:!text-[#F3E5AB] font-semibold transition-colors ml-1.5 underline decoration-[#D4AF37]/40 hover:decoration-[#F3E5AB]",
    footerActionText: "!text-zinc-400 text-xs tracking-wide",
    footer: "!border-t !border-white/5 pt-5 mt-5",
    identityPreviewText: "!text-white font-medium",
    identityPreviewEditButton: "!text-[#D4AF37] hover:!text-[#F3E5AB] text-xs font-mono transition-colors",
    formFieldSuccessText: "!text-emerald-400 text-xs mt-1",
    formFieldErrorText: "!text-rose-400 text-xs mt-1 font-light",
    alertText: "!text-rose-200 text-xs font-light",
    alert: "!bg-rose-950/50 !border !border-rose-500/40 rounded-xl p-3.5 backdrop-blur-md",
  }
};
